defmodule Cyclium.Workflow.Config do
  @moduledoc """
  Parsed workflow configuration generated by `use Cyclium.Workflow`.
  """

  @type t :: %__MODULE__{
          workflow_id: binary(),
          trigger: {:event, binary()} | :manual,
          steps: %{atom() => Cyclium.Workflow.StepConfig.t()},
          failure_policies: %{atom() => map()},
          episode_reuse: boolean(),
          debounce_ms: non_neg_integer() | nil,
          subject_key: atom() | nil
        }

  defstruct [
    :workflow_id,
    :trigger,
    steps: %{},
    failure_policies: %{},
    episode_reuse: true,
    debounce_ms: nil,
    subject_key: nil
  ]
end
